### ISSUE TITLE
Installation fails sporadically, reporting error due to missing 'vagrant-vmware-workstation'

### ISSUE THREAD

**Issue by michaeljb** [nsidc/vagrant-vsphere#115]
```text
mbrandt@nsidc-brandt ~ $ vagrant plugin install vagrant-vsphere
Installing the 'vagrant-vsphere' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Net::HTTPNotFound: No gems found matching "vagrant-vmware-workstation" "3.2.0" nil
mbrandt@nsidc-brandt ~ $
mbrandt@nsidc-brandt ~ $
mbrandt@nsidc-brandt ~ $ vagrant plugin install vagrant-vsphere
Installing the 'vagrant-vsphere' plugin. This can take a few minutes...
Installed the plugin 'vagrant-vsphere (0.19.1)'!
```

We have not tracked down the source of this error, but simply trying again seems to work.

**Comment by mkuzmin** [comment]
It's not related to vagrant-vsphere plugin.
I experience the same issue with other plugins.
Probably this is some kind of network issue on rubygems.org

**Comment by michaeljb** [comment]
Have you experienced this issue with other gems, or only with other gems that are also vagrant plugins?

So far I've only seen this happen with vagrant-vsphere, and it's always talking about "vagrant-vmware-workstation" being missing, so I'm inclined to think it's a problem with the Bundler stuff Vagrant is doing in the background.

**Comment by mkuzmin** [comment]
That's a valid question.
Yes, with vagrant plugins only. All the errors are about vmware-workstation or vmware-fusion.
I think this is an issue reported in https://github.com/mitchellh/vagrant/issues/3764.

**Comment by michael-brandt-cu** [comment]
Vagrant now uses a default retry of 3 when installing gems now, which should resolve this -- mitchellh/vagrant#6097.
