### ISSUE TITLE
Configured resource pool not found when using child resource pool

### ISSUE THREAD

**Issue by mirobeka** [nsidc/vagrant-vsphere#118]
When cloning from template, **vsphere.resource_pool_name** has to be configured properly. When I use child resource pool such as:

    vsphere.resource_pool_name = 'Technology/Applied Research and Development/Test Automation'

I get error **Configured resource pool not found**
But when using root resource pool, it's ok.

    vsphere.resource_pool_name = 'Technology'

Is there any other way how to configure child resource pool?

**Comment by dhallam** [comment]
+1

Same issue for me as well.  Is there a workaround whilst retaining nested resource pools?

**Comment by rylarson** [comment]
Can one of you use rbvmomi to connect to your vsphere instance and list the available resource pools? Post the results here. I am not licensed for it or I would do it myself.

**Comment by michael-brandt-cu** [comment]
Fixed by #189

**Comment by sevensys** [comment]
I'm still struggling with this issue.
I have the following hierarchy of resource pools:
main
 - other
 - mesos
 -openshift

I'm trying to use this parameter:     
    # The resource pool for the new VM
    vsphere.resource_pool_name = 'main/other'

It's not working whereas the value 'main' works.

<img width="946" alt="screen shot 2016-12-01 at 18 58 44" src="https://cloud.githubusercontent.com/assets/393916/20819333/40bae292-b7f9-11e6-89fd-e80e1eaad941.png">
