### ISSUE TITLE
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificat e verify failed

### ISSUE THREAD

**Issue by lioramilbaum** [nsidc/vagrant-vsphere#123]
Hi,

I hit this error when running vagrant up. Listed bellow my vagrantfile. 

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box		= "vsphere"
	config.vm.box_url	= "https://vagrantcloud.com/ssx/boxes/vsphere-dummy/versions/0.0.1/providers/vsphere.box"
		
	config.vm.provider :vsphere do |vsphere|
			
		vsphere.host = 'ilvmvagrant'
		vsphere.compute_resource_name = 'ilvmvagrant'
		vsphere.resource_pool_name = 'ilvmvagrant'
		vsphere.template_name = 'ubuntu12'
		vsphere.name = 'name'
		vsphere.user = 'user'
		vsphere.password = 'password'
		
	end	
end

**Comment by ismben** [comment]
Hi lioramilbaum,
did you find any solution, i'm having the same issue
Thanks

**Comment by lioramilbaum** [comment]
Those settings worked out for me:

			vsphere.host = 'vcenterlan.lmb.com'                           
			vsphere.compute_resource_name = 'ilvmdr.lmb.com'           
			vsphere.resource_pool_name = 'linux'                       
			vsphere.template_name = 'ubuntu'     
			vsphere.name = 'rb-alm-server'                                       
			vsphere.user = 'root'                                   
			vsphere.password = '<password>'                           
			vsphere.insecure = true

**Comment by ismben** [comment]
thank you, it's works for me too
