### ISSUE TITLE
undefined method `[]' for nil:NilClass in close_vsphere action

### ISSUE THREAD

**Issue by jreslock** [nsidc/vagrant-vsphere#124]
I have encountered an issue that appears to be intermittent in nature with `vagrant up --provider=vsphere` and multi-machine configuration.

Here are some details plus a link to a gist for files.

vagrant version 1.7.2
vagrant-vsphere version 1.0.1
vsphere version 5.5.0
guest OS is CentOS 6.4.

Just after 'Setting hostname...' is posted to stdout I receive an error which stops the rest of the vagrant machines from being started.

ERROR:

INFO interface: Machine: error-exit ["VagrantPlugins::VSphere::Errors::VSphereError", "undefined method `[]' for nil:NilClass"]

Gist:  https://gist.github.com/jreslock/a3b1ba8e3f9cc6c1af3b

**Comment by jreslock** [comment]
I was able to resolve this issue by downgrading from vagrant 1.7.2 to 1.6.4.

**Comment by jkugler** [comment]
I am also getting this as well with vagrant-vsphere 1.13.2 and vagrant 2.2.4. This is what I get in my test kichen output:
```
-----> Creating <source-centos-6-bento>...
       Bringing machine 'default' up with 'vsphere' provider...
       ==> default: Calling vSphere CloneVM with the following settings:
       ==> default:  -- Template VM: B5 Lab - Folder/vm/CICD/bento-centos-6.10-x86_64-LATEST
       ==> default:  -- Target VM: B5 Lab - Folder/vm/CICD/source-centos-6-bento-app-access-1551294901-dc
       ==> default: New virtual machine successfully cloned
       ==> default: Waiting for the machine to report its IP address...
           default: Timeout: 240 seconds
           default: IP: 10.199.251.66
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: SSH address: 10.199.251.66:22
           default: SSH username: vagrant
           default: SSH auth method: private key
           default: 
           default: Vagrant insecure key detected. Vagrant will automatically replace
           default: this with a newly generated keypair for better security.
           default: 
           default: Inserting generated public key within guest...
           default: Removing insecure key from the guest if it's present...
           default: Key inserted! Disconnecting and reconnecting using new SSH key...
       ==> default: Machine booted and ready!
       ==> default: Setting hostname...
       undefined method `[]' for nil:NilClass
```
What would be the best way to go about debugging this?

**Comment by jreslock** [comment]
@jkugler You should probably open a new issue for this as my original report is from 2015 and sort of abandoned because I found a workaround.  I'm going to close this issue as I wasn't aware it was still open.
