### ISSUE TITLE
Support for winrm

### ISSUE THREAD

**Issue by cdossantos** [nsidc/vagrant-vsphere#129]
Hello,

I noticed that although I specify in the Vagrantfile the config.vm.communicator as "winrm" (Vagrant version is 1.6.4) the command "vagrant up" halts with the message "Waiting for SSH to become available...". 
I also tried the command "vagrant rdp" and got an error.

**Comment by michael-brandt-cu** [comment]
This should be fixed with v1.6.0. Please re-open this issue if the problem persists.
