### ISSUE TITLE
unable to authenticate

### ISSUE THREAD

**Issue by karnold** [nsidc/vagrant-vsphere#153]
I am unable to authenticate to my vsphere host server. 

```
InvalidLogin: Cannot complete login due to an incorrect user name or password.
```

However I have verified that the login and password are the appropriate credentials and they work just fine in the web client.  This is probably a duh moment, but im not having any luck

```
    vsphere.user = @credentials['vsphere_user']
    vsphere.password = @credentials['vsphere_password'] 
    vsphere.insecure = true
```
Are the settings I am using.  And i can confirm by dumping @credentials that the information is accurate.

**Comment by karnold** [comment]
I've broke this down to as simple as possible and still getting the error

```
    # vSphere Credentials
    vsphere.user = 'MYUSERNAME'
    vsphere.password = :ask
    vsphere.insecure = true

**Comment by karnold** [comment]
figured it out

**Comment by Dooghy** [comment]
Hi karnold,

I'm having the same issue. Can you please provide how you solved this?

**Comment by karnold** [comment]
If i remember correctly, the issue was with the permissions on the account I was using and had nothing to do with this plugin.

**Comment by Dooghy** [comment]
Hi karnold,

Thanks for the reply, By any chance, do you recall if this was a permission issue on the vsphere host or on the compute resource? And by any chance, what permissions you gave to the account you're using?

**Comment by Dooghy** [comment]
Thanks karnold,

It was indeed a permission issue; the guys in charge with vSphere fixed it.

**Comment by deepakmalik85** [comment]
Hi @Dooghy 

I just started facing this issue out of nowhere. Do you remember what permissions were fixed on vsphere that solved this problem?

**Comment by Dooghy** [comment]
@deepakmalik85 Sorry for replying so late ... I don't remember what permissions were required, as these were managed by the client we were implementing the solution. But I remember we asked them to check the account has the required permissions to performs the tasks that vagrant was doing, and after a while it worked. But I don't recall they gave us any details about the permissions. Sorry for not helping.
