### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by viktorbenei** [nsidc/vagrant-vsphere#171]
Seeing that the last commit was in September, last year, I just wanted to ask whether you're still working on this project.

If not, do you have plans to transfer it's ownership, or to invite other collaborators, to make sure this plugin will be maintained?

**Comment by taliesins** [comment]
I also need to make use of this project. I am happy to take over it, if the project is dead.

**Comment by viktorbenei** [comment]
Would be awesome, we at [bitrise](https://www.bitrise.io) are also interested in maintaining the project.

**Comment by mkuzmin** [comment]
Maintainers do a good job merging pull requests and publishing new releases.

You don't need additional permissions to submit new code, or help solving open issues.

**Comment by viktorbenei** [comment]
@mkuzmin   True, that's why it's important to know whether the project still has at least one active maintainer, who can publish new releases. The last code change was more than 4 months ago, and your quite important SSH communicator PR is now open for more than a month, without a merge or rejection. I think in a case like this,  my question, whether the project still has active maintainer(s) or not, is quite important.

**Comment by michael-brandt-cu** [comment]
@viktorbenei This project is not dead! Due to how things work at NSIDC (being a University organization), funding hasn't been consistently available to work on this project, but has more or less come in spikes. However, a new arrangement has just been made that will allow me to regularly devote a portion of my time to this project.

**Comment by viktorbenei** [comment]
That's amazing news @michael-brandt-cu , thank you!
