### ISSUE TITLE
Is this being actively developed?

### ISSUE THREAD

**Issue by bgblanch** [nsidc/vagrant-vsphere#208]
I looked at the code and don't see any work on this project since July.

**Comment by bgblanch** [comment]
I've forked this and will begin work on the bugs & new features in this repo.  You can find the fork at PKWARE/vagrant-vsphere.

**Comment by michael-brandt-cu** [comment]
We don't have much time dedicated to active development on this project, but we do try accept contributions, so it would be great if you could send in pull requests for any bug fixes and new features completed at [PKWARE/vagrant-vsphere](https://github.com/PKWARE/vagrant-vsphere).
