### ISSUE TITLE
Option to define the destination network

### ISSUE THREAD

**Issue by voiprodrigo** [nsidc/vagrant-vsphere#213]
Hi,

With customisation spec, you have a way to set the IP address and hostname from Vagrant. Is it also possible somehow to define the network/switch to be used, overriding the setting on the source?

Thanks

**Comment by voiprodrigo** [comment]
Duplicate of #209

**Comment by lynic** [comment]
After go through the codes, I found that 'vlan' is actually the portgroup name to be used for first network adapter.
