### ISSUE TITLE
waiting for sysprep breaks linked clones

### ISSUE THREAD

**Issue by ggascoigne** [nsidc/vagrant-vsphere#222]
We use linked clones, it makes provisioning short term Windows tests boxes incredibly fast.  The new "wait for Sysprep" change that went into 1.11.0 causes vagrant to never notice that these boxes have booted.  It just sits there saying "waiting for Sysprep" until it times out.

1.10.1 still works perfectly.

**Comment by rhydian76** [comment]
I also have the issue whereby sysprep doesnt notice the box has booted and times out after the "waiting for Sysprep" phase. Still seems broken in 1.11.1.
