### ISSUE TITLE
Open-vm-tools & static IP allocation with a VMWare customization spec

### ISSUE THREAD

**Issue by rhydian76** [nsidc/vagrant-vsphere#236]
There seems to be an issue whereby when you allocate a static IP the vagrant file using config.vm.network (for example config.vm.network 'private_network', ip: '192.168.50.4'), and specifying a customization_spec_name, - if the template machine is running open-vm-tools (as recommended) and not the official VMware tools package, the address allocation fails and the deployment process fails. If the image has the official VMware tools package then deployment succeeds by first getting the IP from the customization spec and then swapping to the allocated IP in the vagrant file.

Not sure if this is an issue with vagrant-vsphere or if its something open-vm-tools is doing and not able to read the customization spec, but thought I`d flag it as a potential issue as others may be getting this problem also.

My deployment is based on vagrant-vsphere 1.12.0, vagrant 1.9.1, and the machine Im deploying is a CentOS 7 x64 VM.

**Comment by nickkeyzer** [comment]
Try installing perl in your CentOS 7 template. I ran into a similar issue using Terraform with vCenter and Centos 7.3. open-vm-tools has a perl dependency that causes guess customization to fail. 

See: [https://www.reddit.com/r/vmware/comments/3d6k7i/centos_7_openvmtoolsdeploypkg_not_taking/#bottom-comments](https://www.reddit.com/r/vmware/comments/3d6k7i/centos_7_openvmtoolsdeploypkg_not_taking/#bottom-comments)

**Comment by rhydian76** [comment]
@nickkeyzer Thanks for this. Ill give this a go when I get a few minutes spare, and report back.

**Comment by rhydian76** [comment]
This was fixed as per @nickkeyzer's solution
