### ISSUE TITLE
Credentials file

### ISSUE THREAD

**Issue by ticktockhouse** [nsidc/vagrant-vsphere#249]
It could be considered insecure and/or inconvenient to have to have vsphere credentials within your Vagrantfile. Is it possible to place credentials outside the Vagrantfile, and refer to them from there?

**Comment by michael-brandt-cu** [comment]
The Vagrantfile is just Ruby, so you could do something like this:

```ruby
Vagrant.configure("2") do |config|
  config.vm.provider :vsphere do |vsphere|
    vsphere.user = File.read('vsphere_user.txt')
    vsphere.password = File.read(vsphere_password.txt')
  end
end
```
