### ISSUE TITLE
Prompt vsphere password programatically 

### ISSUE THREAD

**Issue by ezlee** [nsidc/vagrant-vsphere#304]
When running "vagrant up" to create a VM from a template, vsphere.password is required to authentication to vsphere environment.

Is there a way not to put "vsphere.password=<password>" into the Vagrantfile?
I am trying to run test kitchen and use the vagrant driver, but I don't want to hard code the vsphere.password into the Vagrantfile.

thanks!

**Comment by MattF-NSIDC** [comment]
@ezlee for those coming to this issue from a Google search, can you share what you did to resolve?
