### ISSUE TITLE
Add the support of VM launching in parallel

### ISSUE THREAD

**Issue by henrysher** [nsidc/vagrant-vsphere#32]
It takes much time when we need to clone multiple VMs from a template in a queue.
If we could support VM launching in parallel, it would be great!

**Comment by marnovdm** [comment]
This works really well and greatly speeds up provisioning, thanks for this!

One minor request would be to also destroy the VMs in parallel if possible? I noticed that still happens sequentially, and for testing we deploy and remove a lot of VMs.
