### ISSUE TITLE
"vagrant halt" and "vagrant suspend" emit scary error messages

### ISSUE THREAD

**Issue by offby1** [nsidc/vagrant-vsphere#8]
Unfortunately I don't know enough about either Vagrant or vSphere to describe in detail what I did.  But I successfully did "vagrant up", and observed (from the vSphere web client) that there was a new virtual machine; then I tried "vagrant halt" and saw this:

```
:( 1 10:02:55 [erichanchrow@Eric-Hanchrows-iMac vagrant] (vagrant-vsphere)$ vagrant halt
Vagrant attempted to call the action 'halt' on the provider
'vSphere (42094cca-9310-8a1a-0fa5-7d31210fe7d0)', but this provider doesn't support this action. This
is probably a bug in either the provider or the plugin calling this
action, and should be reported.
:( 1 10:02:55 [erichanchrow@Eric-Hanchrows-iMac vagrant] (vagrant-vsphere)$ vagrant suspend
Vagrant attempted to call the action 'suspend' on the provider
'vSphere (42094cca-9310-8a1a-0fa5-7d31210fe7d0)', but this provider doesn't support this action. This
is probably a bug in either the provider or the plugin calling this
action, and should be reported.
```

**Comment by dhirajdp** [comment]
is this issue fixed.?

**Comment by michael-brandt-cu** [comment]
Looks like it's fixed for `halt` but not for `suspend`.

```
mbrandt@nsidc-brandt ~/projects/vagrant-vsphere-example
  > vagrant up
Bringing machine 'default' up with 'vsphere' provider...
==> default: Calling vSphere CloneVM with the following settings:
==> default:  -- Template VM: NSIDC/vm/Linux/SCM/trusty64-nsidc
==> default:  -- Target VM: NSIDC/vm/Linux/SCM/dev/mbrandt-vsphere-pr-testing
==> default: New virtual machine successfully cloned
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 172.18.225.242:22
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Rsyncing folder: /Users/mbrandt/projects/vagrant-vsphere-example/ => /vagrant

mbrandt@nsidc-brandt ~/projects/vagrant-vsphere-example
  > vagrant halt
==> default: Attempting graceful shutdown of VM...

mbrandt@nsidc-brandt ~/projects/vagrant-vsphere-example
  > vagrant up
Bringing machine 'default' up with 'vsphere' provider...
==> default: The VM is already created
==> default: Calling vSphere PowerOn
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 172.18.225.242:22
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Rsyncing folder: /Users/mbrandt/projects/vagrant-vsphere-example/ => /vagrant
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

mbrandt@nsidc-brandt ~/projects/vagrant-vsphere-example
  > vagrant suspend
Vagrant attempted to call the action 'suspend' on the provider
'vSphere (42059517-6fb8-51ac-62da-bfb633468e8b)', but this provider doesn't support this action. This
is probably a bug in either the provider or the plugin calling this
action, and should be reported.
```

**Comment by dhirajdp** [comment]
thanks for reply

On Thu, Jun 2, 2016 at 7:51 PM, Michael Brandt <notifications@github.com>
wrote:

> Looks like it's fixed for halt but not for suspend.
>
> mbrandt@nsidc-brandt ~/projects/vagrant-vsphere-example
>   > vagrant up
> Bringing machine 'default' up with 'vsphere' provider...
> ==> default: Calling vSphere CloneVM with the following settings:
> ==> default:  -- Template VM: NSIDC/vm/Linux/SCM/trusty64-nsidc
> ==> default:  -- Target VM: NSIDC/vm/Linux/SCM/dev/mbrandt-vsphere-pr-testing
> ==> default: New virtual machine successfully cloned
> ==> default: Waiting for machine to boot. This may take a few minutes...
>     default: SSH address: 172.18.225.242:22
>     default: SSH username: vagrant
>     default: SSH auth method: private key
> ==> default: Machine booted and ready!
> ==> default: Rsyncing folder: /Users/mbrandt/projects/vagrant-vsphere-example/ => /vagrant
>
> mbrandt@nsidc-brandt ~/projects/vagrant-vsphere-example
>   > vagrant halt
> ==> default: Attempting graceful shutdown of VM...
>
> mbrandt@nsidc-brandt ~/projects/vagrant-vsphere-example
>   > vagrant up
> Bringing machine 'default' up with 'vsphere' provider...
> ==> default: The VM is already created
> ==> default: Calling vSphere PowerOn
> ==> default: Waiting for machine to boot. This may take a few minutes...
>     default: SSH address: 172.18.225.242:22
>     default: SSH username: vagrant
>     default: SSH auth method: private key
> ==> default: Machine booted and ready!
> ==> default: Rsyncing folder: /Users/mbrandt/projects/vagrant-vsphere-example/ => /vagrant
> ==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
> ==> default: flag to force provisioning. Provisioners marked to run always will still run.
>
> mbrandt@nsidc-brandt ~/projects/vagrant-vsphere-example
>   > vagrant suspend
> Vagrant attempted to call the action 'suspend' on the provider
> 'vSphere (42059517-6fb8-51ac-62da-bfb633468e8b)', but this provider doesn't support this action. This
> is probably a bug in either the provider or the plugin calling this
> action, and should be reported.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/nsidc/vagrant-vsphere/issues/8#issuecomment-223306550>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASyksxzoMBHulnxvnqSb7VLT7wcSmT7Bks5qHubMgaJpZM4A61OZ>
> .
>



-- 
Regards

DHIRAJ PANDEY
