### ISSUE TITLE
Configured compute resource not found

### ISSUE THREAD

**Issue by Zoooook** [nsidc/vagrant-vsphere#89]
Here's my Vagrantfile:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'dummy.box'

  config.vm.provider :vsphere do |vsphere|
    vsphere.host = 'vcprodsrv1.***.com'
    vsphere.compute_resource_name = 'esxpsrv5.***.com'
    vsphere.template_name = '***/chefnode'
    vsphere.name = 'vagranttest'
    vsphere.user = 'vagrantadmin'
    vsphere.password = '***'
    vsphere.insecure = true
  end
end
```

When I run vagrant up --provider=vsphere --debug, I get this:

```
ERROR warden: Error occurred: Configured compute resource not found
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Configured compute resource not found
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Configured compute resource not found
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x007f9040f42900>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-81dbdd568f1311ee6fcc6756033d00fd
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x007f9040ee4878>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::VSphere::Errors::VSphereError: Configured compute resource not found>
ERROR vagrant: Configured compute resource not found
ERROR vagrant: /home/user/.vagrant.d/gems/gems/vagrant-vsphere-0.13.0/lib/vSphere/util/vim_helpers.rb:18:in `get_resource_pool'
/home/user/.vagrant.d/gems/gems/vagrant-vsphere-0.13.0/lib/vSphere/action/clone.rb:117:in `get_location'
/home/user/.vagrant.d/gems/gems/vagrant-vsphere-0.13.0/lib/vSphere/action/clone.rb:29:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
/home/user/.vagrant.d/gems/gems/vagrant-vsphere-0.13.0/lib/vSphere/action/connect_vsphere.rb:19:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:196:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:173:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/environment.rb:434:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:161:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:161:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
 INFO interface: error: Configured compute resource not found
Configured compute resource not found
 INFO interface: Machine: error-exit ["VagrantPlugins::VSphere::Errors::VSphereError", "Configured compute resource not found"]
```

But it has the right name...

![vagrant1](https://cloud.githubusercontent.com/assets/8059701/4252048/438e170a-3a92-11e4-8b16-03d9cd27087b.png)

![vagrant2](https://cloud.githubusercontent.com/assets/8059701/4252051/46dacdfe-3a92-11e4-9f45-c77dce61df01.png)

I've tried changing vsphere.compute_resource_name to `TestDev/esxpsrv5.***.com` and also to `C***/TestDev/esxpsrv5.***.com`, with no luck

I've put some debug tags in vim_helpers.rb

```
print get_datacenter(connection,machine)
# Datacenter("datacenter-3")
print machine.provider_config.compute_resource_name
# esxpsrv5.***.com
```

and in lib/rbvmomi/vim/Datacenter.rb:

```
print path
# esxpsrv5.***.com
print hostFolder
# Folder("group-h5")
```

Any ideas?

**Comment by karnold** [comment]
Im running into the exact same issue.  Using the name of the cluster will get the VM to provision, however I need to specifically provision it to a host within the cluster.  is there another setting that I should be using to clone to a specific host or is this just not supported?

**Comment by Zoooook** [comment]
Not sure. Have you tried the resource_pool_name property? Take a look at this: https://github.com/nsidc/vagrant-vsphere/pull/152

**Comment by karnold** [comment]
I have, using the following:

```
  vsphere.data_center_name = 'DOMAIN'
  vsphere.resource_pool_name = 'marjorie.XXX.org'
  vsphere.compute_resource_name = 'iCluster'

```
  
Here is the layout in the vSphere Client:

![screen shot 2015-10-20 at 1 01 23 pm](https://cloud.githubusercontent.com/assets/1236813/10619556/23cd8b72-772b-11e5-8ce9-b3b4aa08acf8.png)

when doing so it returns "Configured resource pool not found"

this commit you referenced seems promising however.

**Comment by Kuberboef** [comment]
I am a little new here, but I would suggest this.

    vsphere.compute_resource_name = '10.1.202.10'
    vsphere.vm_base_path = 'Dev_Ops'
    vsphere.data_center_name = 'COMP_Dev'

On Tue, Oct 20, 2015 at 7:05 PM, Kristen Arnold <notifications@github.com>
wrote:

> Im running into the exact same issue. Using the name of the cluster will
> get the VM to provision, however I need to specifically provision it to a
> host within the cluster. is there another setting that I should be using to
> clone to a specific host or is this just not supported?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nsidc/vagrant-vsphere/issues/89#issuecomment-149634618>
> .
>



-- 
J Stefaans Mostert
Mobile: 0844634590
Fax: 0867300603
skype: mozzi_za (kuberboef)

Linux is simple. It just takes a genius to understand its simplicity.

**Comment by Dooghy** [comment]
Hi guys,
Having the same issue: not being able to provision the vm to a specific host (i can do it just fine in the cluster). 
Did you find any solution to this that you can share?

**Comment by karnold** [comment]
I never did.  I eventually just bailed on this plugin because of it

**Comment by mmendez97** [comment]
Changing the IP ESXi host for Cluster name works for me perfect. Thanks. Please do not forget these symbols    '  '

Vagrant.configure("2") do |config|
  config.vm.box = "vsphere-dummy"

  config.vm.provider :vsphere do |vsphere|
    # The vSphere host we're going to connect to
    vsphere.host = 'Write the vCenter Server IP'

   # The ESX host for the new VM
    vsphere.compute_resource_name = 'Write Cluster-Name'

    # The resource pool for the new VM
    vsphere.resource_pool_name = 'Write Resouce pool name'

    # The template we're going to clone
    vsphere.template_name = 'Write Template-Name'

    # The name of the new machine
    vsphere.name = 'centos7.mynewbox'

    # vSphere login
    vsphere.user = 'administrator@*********.local'

    # vSphere password
    vsphere.password = '**********'

    # If you don't have SSL configured correctly, set this to 'true'
    vsphere.insecure = true
  end
